/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gpac_Osmo4_MobilinsightReceiver */

#ifndef _Included_com_gpac_Osmo4_MobilinsightReceiver
#define _Included_com_gpac_Osmo4_MobilinsightReceiver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gpac_Osmo4_MobilinsightReceiver
 * Method:    setPHYBandwidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_gpac_Osmo4_MobilinsightReceiver_setPHYBandwidth
  (JNIEnv *, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
